/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicauca.cuychair.gui.gui.views;

/**
 *
 * @author Frdy
 */
public class AlertSimple extends javax.swing.JFrame {

    /**
     * Creates new form Alert
     * @param title titulo del modal
     * @param descripcion descripcion del modal
     */
    public AlertSimple(String title, String descripcion) {        
        initComponents();
        // EXTENDED COMPONENT INITIALIZATION
        this.jLabelTitulo.setText(title);        
        this.jLabelDescripcion.setText(descripcion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jPanelActions = new javax.swing.JPanel();
        jButtonContinue = new javax.swing.JButton();
        jLabelDescripcion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Título");
        jLabelTitulo.setPreferredSize(new java.awt.Dimension(70, 40));
        getContentPane().add(jLabelTitulo, java.awt.BorderLayout.PAGE_START);

        jPanelActions.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonContinue.setText("Continuar");
        jButtonContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinueActionPerformed(evt);
            }
        });
        jPanelActions.add(jButtonContinue);

        getContentPane().add(jPanelActions, java.awt.BorderLayout.PAGE_END);

        jLabelDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDescripcion.setText("Descripción");
        jLabelDescripcion.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelDescripcion.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabelDescripcion, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinueActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonContinueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonContinue;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelActions;
    // End of variables declaration//GEN-END:variables
}
