/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicauca.cuychair.gui.gui.views;

import co.edu.unicauca.cuychair.gui.gui.Context.AppContext;
import co.edu.unicauca.cuychair.gui.gui.DTO.PaperDTO;
import co.edu.unicauca.cuychair.gui.gui.DTO.UserDTO;
import co.edu.unicauca.cuychair.gui.gui.services.PaperServices;

import javax.swing.*;
import java.util.List;

import static co.edu.unicauca.cuychair.gui.gui.views.utilities.Utilities.setAlert;

/**
 *
 * @author usuario
 */
public class ViewAddPapers extends javax.swing.JFrame {

    private PaperServices servicesPaper;
    private UserDTO usersContext;
    /**
     * Creates new form ViewAddPapers
     */
    public ViewAddPapers() {
        AppContext appContext = AppContext.getInstance();
        servicesPaper = appContext.getPaperService();
        usersContext = appContext.getLoggedUser();
        initComponents();
        updateConferences();
    }

    public void updateConferences(){
        List<Integer> IdsConferences=servicesPaper.conferencesByAuthor(usersContext);
        for(Integer id : IdsConferences){
            jComboBoxConferencesId.addItem(id.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Head = new javax.swing.JPanel();
        JLabelTitle = new javax.swing.JLabel();
        jLabelConferenceId = new javax.swing.JLabel();
        jLabelTitlePaper = new javax.swing.JLabel();
        jLabelAbstract = new javax.swing.JLabel();
        jLabelSubtitle = new javax.swing.JLabel();
        TextFieldTitulo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaAbstract = new javax.swing.JTextArea();
        TextFieldSubtitulo = new javax.swing.JTextField();
        jComboBoxConferencesId = new javax.swing.JComboBox<>();
        jButtonSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Head.setBackground(new java.awt.Color(199, 213, 224));

        JLabelTitle.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        JLabelTitle.setForeground(new java.awt.Color(0, 0, 0));
        JLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelTitle.setText("Paper");

        javax.swing.GroupLayout HeadLayout = new javax.swing.GroupLayout(Head);
        Head.setLayout(HeadLayout);
        HeadLayout.setHorizontalGroup(
            HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HeadLayout.setVerticalGroup(
            HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        jLabelConferenceId.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabelConferenceId.setText("Conferencia");

        jLabelTitlePaper.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabelTitlePaper.setText("Titulo");

        jLabelAbstract.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabelAbstract.setText("Resumen");

        jLabelSubtitle.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabelSubtitle.setText("Subtitulo");

        TextAreaAbstract.setColumns(20);
        TextAreaAbstract.setRows(5);
        jScrollPane1.setViewportView(TextAreaAbstract);

        jComboBoxConferencesId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonSave.setBackground(new java.awt.Color(102, 192, 244));
        jButtonSave.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jButtonSave.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSave.setText("Guardar");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Head, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelTitlePaper, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelAbstract, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabelConferenceId)
                                .addGap(33, 33, 33)
                                .addComponent(jComboBoxConferencesId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldSubtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 67, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSave)
                .addGap(164, 164, 164))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Head, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTitlePaper)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAbstract)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSubtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextFieldSubtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConferenceId)
                    .addComponent(jComboBoxConferencesId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        PaperDTO paperDTO=new PaperDTO();
        String title=TextFieldTitulo.getText();
        String Abstract=TextAreaAbstract.getText();
        String subtitulo=TextFieldSubtitulo.getText();
        String conferenceId=jComboBoxConferencesId.getSelectedItem().toString();
        if(title==null||Abstract==null||subtitulo==null){
            setAlert("Error al guardar Paper", "Espacios en blanco");
            return;
        }else{
            paperDTO.setTitle(title);
            paperDTO.setAbstract(Abstract);
            paperDTO.setSubTitle(subtitulo);
            paperDTO.setIdAuthor(usersContext.getId());
            paperDTO.setIdConference(Integer.parseInt(conferenceId));
            servicesPaper.addPaper(paperDTO);
            JOptionPane.showMessageDialog(null, "Paper guardado exitosamente");
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Head;
    private javax.swing.JLabel JLabelTitle;
    private javax.swing.JTextArea TextAreaAbstract;
    private javax.swing.JTextField TextFieldSubtitulo;
    private javax.swing.JTextField TextFieldTitulo;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox<String> jComboBoxConferencesId;
    private javax.swing.JLabel jLabelAbstract;
    private javax.swing.JLabel jLabelConferenceId;
    private javax.swing.JLabel jLabelSubtitle;
    private javax.swing.JLabel jLabelTitlePaper;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
