/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicauca.cuychair.gui.gui.views;

import co.edu.unicauca.cuychair.gui.gui.Context.AppContext;
import co.edu.unicauca.cuychair.gui.gui.DTO.UserDTO;
import co.edu.unicauca.cuychair.gui.gui.DTO.conferenceAPI.ConferenceDTO;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author julia
 */
public class ViewListConferences extends javax.swing.JFrame {

    /**
     * Creates new form ViewListConferences
     */
    public ViewListConferences() {
        this.tableModel = new DefaultTableModel(
                new Object [][] {},
            new String [] { "Titulo", "Tema", "Descripcion" }
        );
        initComponents();
        
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelMainTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConferences = new javax.swing.JTable();
        jButtonAddConference = new javax.swing.JButton();
        jButtonAddConference1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelMainTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelMainTitle.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMainTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMainTitle.setText("CONFERENCIAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelMainTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMainTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jTableConferences.setModel(this.tableModel);
        jScrollPane1.setViewportView(jTableConferences);
        if (jTableConferences.getColumnModel().getColumnCount() > 0) {
            jTableConferences.getColumnModel().getColumn(0).setPreferredWidth(6);
            jTableConferences.getColumnModel().getColumn(1).setPreferredWidth(6);
        }

        jButtonAddConference.setBackground(new java.awt.Color(102, 192, 244));
        jButtonAddConference.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAddConference.setText("Registrar conferencia");
        jButtonAddConference.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddConferenceActionPerformed(evt);
            }
        });

        jButtonAddConference1.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.GreyInline"));
        jButtonAddConference1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAddConference1.setText("Refrescar");
        jButtonAddConference1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddConference1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonAddConference)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAddConference1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddConference)
                    .addComponent(jButtonAddConference1))
                .addGap(53, 53, 53))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddConferenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddConferenceActionPerformed
        ViewAddConference viewAddConferences = new ViewAddConference();
        viewAddConferences.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        viewAddConferences.setVisible(true);
    }//GEN-LAST:event_jButtonAddConferenceActionPerformed

    private void jButtonAddConference1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddConference1ActionPerformed
        refreshTable();
        
    }//GEN-LAST:event_jButtonAddConference1ActionPerformed

    void refreshTable() {
        AppContext ctx = AppContext.getInstance();
        UserDTO loggedOne = ctx.getLoggedUser();
        List<ConferenceDTO> conferences = ctx.getConferenceService().getAllConferences();
        tableModel.setRowCount(0);
        for (ConferenceDTO c : conferences) {
            Object[] rowData = {c.getTitle(), c.getSubject(), c.getDescription()};
            this.tableModel.addRow(rowData);
            System.out.println("id: " + c.getId());
        }
    }
    
    private DefaultTableModel tableModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddConference;
    private javax.swing.JButton jButtonAddConference1;
    private javax.swing.JLabel jLabelMainTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConferences;
    // End of variables declaration//GEN-END:variables
}
