/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicauca.cuychair.gui.gui.views;

import co.edu.unicauca.cuychair.gui.gui.Context.AppContext;
import co.edu.unicauca.cuychair.gui.gui.DTO.PaperDTO;
import co.edu.unicauca.cuychair.gui.gui.DTO.UserDTO;
import co.edu.unicauca.cuychair.gui.gui.services.PaperServices;
import co.edu.unicauca.cuychair.gui.gui.views.utilities.ButtonEditor;
import co.edu.unicauca.cuychair.gui.gui.views.utilities.ButtonRenderer;
import co.edu.unicauca.cuychair.gui.gui.views.utilities.ListPaperModel;

import javax.swing.*;
import java.util.ArrayList;
import java.util.List;
/**
 *
 * @author usuario
 */
public class ViewListPaper extends javax.swing.JFrame {

    private PaperServices servicesPaper;
    private UserDTO usersContext;

    /**
     * Creates new form ViewListPaper
     */
    public ViewListPaper() {
        AppContext appContext = AppContext.getInstance();
        servicesPaper = appContext.getPaperService();
        usersContext = appContext.getLoggedUser();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Head = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablePapers = new javax.swing.JTable();
        buttonListPaper = new javax.swing.JButton();
        jButtonCreatePaper = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Head.setBackground(new java.awt.Color(199, 213, 224));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lista Paper");

        javax.swing.GroupLayout HeadLayout = new javax.swing.GroupLayout(Head);
        Head.setLayout(HeadLayout);
        HeadLayout.setHorizontalGroup(
            HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HeadLayout.setVerticalGroup(
            HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        TablePapers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablePapers.setRowHeight(70);
        jScrollPane1.setViewportView(TablePapers);

        buttonListPaper.setBackground(new java.awt.Color(102, 192, 244));
        buttonListPaper.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        buttonListPaper.setForeground(new java.awt.Color(0, 0, 0));
        buttonListPaper.setText("Listar Papers");
        buttonListPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonListPaperActionPerformed(evt);
            }
        });

        jButtonCreatePaper.setBackground(new java.awt.Color(102, 192, 244));
        jButtonCreatePaper.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jButtonCreatePaper.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCreatePaper.setText("Crear Paper");
        jButtonCreatePaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreatePaperActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Head, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(buttonListPaper)
                        .addGap(69, 69, 69)
                        .addComponent(jButtonCreatePaper)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Head, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonListPaper)
                    .addComponent(jButtonCreatePaper))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonListPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonListPaperActionPerformed
        List<PaperDTO> papers=servicesPaper.getPapersByAuthor(usersContext.getId());
        ListPaperModel model=new ListPaperModel(papers);
        TablePapers.setModel(model);
        
        TablePapers.getColumn("Acciones").setCellRenderer(new ButtonRenderer());
        TablePapers.getColumn("Acciones").setCellEditor(new ButtonEditor(TablePapers,papers));
    }//GEN-LAST:event_buttonListPaperActionPerformed

    private void jButtonCreatePaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreatePaperActionPerformed
        ViewAddPapers viewAddPapers=new ViewAddPapers();
        viewAddPapers.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        viewAddPapers.setVisible(true);
    }//GEN-LAST:event_jButtonCreatePaperActionPerformed
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Head;
    private javax.swing.JTable TablePapers;
    private javax.swing.JButton buttonListPaper;
    private javax.swing.JButton jButtonCreatePaper;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
